apiVersion: batch/v1
kind: CronJob
metadata:
  name: nuudel-form-submit
spec:
  jobTemplate:
    metadata:
      name: nuudel-form-submit
    spec:
      template:
        spec:
          containers:
            - name: nuudel-form-submit
              image: registry.access.redhat.com/ubi9
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
              args:
                - -c
                - curl -s https://raw.githubusercontent.com/bliemli/nuudel-form-submitter/main/nuudel-form-submit.sh | bash
              env:
                - name: NUUDEL_ADMIN_URL
                  valueFrom:
                    secretKeyRef:
                      name: nuudel-form-submit-url
                      key: url
          restartPolicy: OnFailure
  schedule: 0 0 * * 0
